### ISSUE TITLE
Error in the sum of passed tests

### ISSUE THREAD

**Issue by zatolokinboris** [neochae1/upload-test-result#1]
Hello! 
I found this error:
when slack receives a message in the passed tests section, all the tests that are in the project are displayed. Also, the total amount of tests is written incorrectly by adding the passed and missed tests. And the report is misleading.

In the attachment there is an example of how the report is displayed in the github action - how many tests are in total, how many passed and how many were skipped. As well as a screenshot of your report. Which counted in general all tests as passed.

![image](https://user-images.githubusercontent.com/69625105/199479990-f73ebb07-59f6-4c41-b275-76c325599893.png)
![image](https://user-images.githubusercontent.com/69625105/199480619-25e7b1c1-46cd-42a2-8eb4-fed92fd0edec.png)

**Comment by neochae1** [comment]
@zatolokinboris Thanks for your reporting.
Total means Passed + Failed + Skipped and that is the intended operation.
Total does not means how many really tested. 

Successfully Tested = "Passed"
Failed Tests = "Failed"
Skipped Tested = "Skipped"

The total Tests are the sum of them.

**Comment by zatolokinboris** [comment]
@neochae1 Thanks for the answer. I understood about the total number. 
But I have a question about the display - successfully completed tests.

In my screenshots, you can see that 22 tests are displayed in successfully completed tests.
Whereas in reality I have only 22 of them.
5 are run into the github action, the rest are marked with an annotation ignore and are displayed as 17 skipped.

This means that only 5 tests should be displayed in the passed field.
Can you help sort this out?

Or I don't understand something?

**Comment by neochae1** [comment]
@zatolokinboris 
Ok, I got it. You're right.

In your case,
"Successfully Tested"  should have "5"
"Total Tested" should have "22"

**Comment by neochae1** [comment]
I have fixed with below PR.
Please check your result and let me know your result.

https://github.com/neochae1/upload-test-result/pull/2/files

**Comment by zatolokinboris** [comment]
Would you create a new realise for checking in GitHub Actions workflow please ?

**Comment by zatolokinboris** [comment]
@neochae1 
Cause right now I'm getting the same result

**Comment by zatolokinboris** [comment]
@neochae1 Hi! Please tell me there is some news?

**Comment by neochae1** [comment]
I made a new tags 1.0.1
https://github.com/marketplace/actions/junit-slack-reporter-with-coverage?version=v1.0.1

Check and share the result.
neochae1/upload-test-result@v1.0.1

**Comment by zatolokinboris** [comment]
@neochae1 Thanks! Now it works!
![Снимок](https://user-images.githubusercontent.com/69625105/202098320-a07a69d1-092e-41e5-926f-c136ed1cb498.JPG)
